// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utoilskthbtlqgpjauui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0b2lsc2t0aGJ0bHFncGphdXVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzM2MjYsImV4cCI6MjA2Mzg0OTYyNn0.ZNLD_MB-Juc1dSJ1UMMmXpT8UzrBH-JFguyQiUZdDqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);